# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aura' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aura
  pod 'GoogleMaps'


  target 'Aura-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Aura-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aura-tvOS

  target 'Aura-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
